# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/florian/Desktop/ProjetTetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/florian/Desktop/ProjetTetris

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/florian/Desktop/ProjetTetris/CMakeFiles /Users/florian/Desktop/ProjetTetris//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/florian/Desktop/ProjetTetris/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tetris

# Build rule for target.
Tetris: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tetris
.PHONY : Tetris

# fast build rule for target.
Tetris/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/build
.PHONY : Tetris/fast

GraphicsObject.o: GraphicsObject.cpp.o

.PHONY : GraphicsObject.o

# target to build an object file
GraphicsObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/GraphicsObject.cpp.o
.PHONY : GraphicsObject.cpp.o

GraphicsObject.i: GraphicsObject.cpp.i

.PHONY : GraphicsObject.i

# target to preprocess a source file
GraphicsObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/GraphicsObject.cpp.i
.PHONY : GraphicsObject.cpp.i

GraphicsObject.s: GraphicsObject.cpp.s

.PHONY : GraphicsObject.s

# target to generate assembly for a file
GraphicsObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/GraphicsObject.cpp.s
.PHONY : GraphicsObject.cpp.s

Shapes.o: Shapes.cpp.o

.PHONY : Shapes.o

# target to build an object file
Shapes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Shapes.cpp.o
.PHONY : Shapes.cpp.o

Shapes.i: Shapes.cpp.i

.PHONY : Shapes.i

# target to preprocess a source file
Shapes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Shapes.cpp.i
.PHONY : Shapes.cpp.i

Shapes.s: Shapes.cpp.s

.PHONY : Shapes.s

# target to generate assembly for a file
Shapes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/Shapes.cpp.s
.PHONY : Shapes.cpp.s

ball.o: ball.cpp.o

.PHONY : ball.o

# target to build an object file
ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/ball.cpp.o
.PHONY : ball.cpp.o

ball.i: ball.cpp.i

.PHONY : ball.i

# target to preprocess a source file
ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/ball.cpp.i
.PHONY : ball.cpp.i

ball.s: ball.cpp.s

.PHONY : ball.s

# target to generate assembly for a file
ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/ball.cpp.s
.PHONY : ball.cpp.s

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/game.cpp.s
.PHONY : game.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.s
.PHONY : main.cpp.s

sprite.o: sprite.cpp.o

.PHONY : sprite.o

# target to build an object file
sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/sprite.cpp.o
.PHONY : sprite.cpp.o

sprite.i: sprite.cpp.i

.PHONY : sprite.i

# target to preprocess a source file
sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/sprite.cpp.i
.PHONY : sprite.cpp.i

sprite.s: sprite.cpp.s

.PHONY : sprite.s

# target to generate assembly for a file
sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/sprite.cpp.s
.PHONY : sprite.cpp.s

surface.o: surface.cpp.o

.PHONY : surface.o

# target to build an object file
surface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/surface.cpp.o
.PHONY : surface.cpp.o

surface.i: surface.cpp.i

.PHONY : surface.i

# target to preprocess a source file
surface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/surface.cpp.i
.PHONY : surface.cpp.i

surface.s: surface.cpp.s

.PHONY : surface.s

# target to generate assembly for a file
surface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/surface.cpp.s
.PHONY : surface.cpp.s

window.o: window.cpp.o

.PHONY : window.o

# target to build an object file
window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/window.cpp.o
.PHONY : window.cpp.o

window.i: window.cpp.i

.PHONY : window.i

# target to preprocess a source file
window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/window.cpp.i
.PHONY : window.cpp.i

window.s: window.cpp.s

.PHONY : window.s

# target to generate assembly for a file
window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/window.cpp.s
.PHONY : window.cpp.s

window_surface.o: window_surface.cpp.o

.PHONY : window_surface.o

# target to build an object file
window_surface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/window_surface.cpp.o
.PHONY : window_surface.cpp.o

window_surface.i: window_surface.cpp.i

.PHONY : window_surface.i

# target to preprocess a source file
window_surface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/window_surface.cpp.i
.PHONY : window_surface.cpp.i

window_surface.s: window_surface.cpp.s

.PHONY : window_surface.s

# target to generate assembly for a file
window_surface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/window_surface.cpp.s
.PHONY : window_surface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tetris"
	@echo "... GraphicsObject.o"
	@echo "... GraphicsObject.i"
	@echo "... GraphicsObject.s"
	@echo "... Shapes.o"
	@echo "... Shapes.i"
	@echo "... Shapes.s"
	@echo "... ball.o"
	@echo "... ball.i"
	@echo "... ball.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sprite.o"
	@echo "... sprite.i"
	@echo "... sprite.s"
	@echo "... surface.o"
	@echo "... surface.i"
	@echo "... surface.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
	@echo "... window_surface.o"
	@echo "... window_surface.i"
	@echo "... window_surface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

